# Generated by Django 4.0.6 on 2022-07-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cpu_ecc_alter_cpu_pci_alter_cpu_pci_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='pr_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
