# Generated by Django 4.0.6 on 2022-07-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_upload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(default='bbrruuhh.oooppp', max_length=50),
        ),
    ]
