# Generated by Django 4.0.6 on 2022-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_upload_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='image_id',
        ),
        migrations.AddField(
            model_name='opinion',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
